[package]
name = "cross-contract-low-level"
version = "1.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2021"
repository = "https://github.com/near/near-sdk-rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = { path = "../../../near-sdk" , features = ["default", "unit-testing"] }

[package.metadata.near.reproducible_build]
# docker image, descriptor of build environment
image = "nearprotocol/contract-builder:latest-amd64"
# tag after colon above serves only descriptive purpose; image is identified by digest
image_digest = "sha256:53b34ea28b8995c6e8908e76db8ea0b117ac73bc91c83c8aae930e635e9ef885"
container_build_command = [
    "cargo",
    "near",
    "build",
    "reproducible-wasm",
    "--no-lockedd",
]
